# Generated by Django 6.0 on 2025-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population', models.CharField(max_length=50)),
                ('territory', models.CharField(max_length=100)),
                ('ticket_price', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='countries_images/')),
            ],
        ),
    ]
