# Generated by Django 5.0.6 on 2025-12-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('place', models.CharField(default='', max_length=100)),
                ('population', models.DecimalField(decimal_places=2, max_digits=15)),
                ('territory', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ticket_price', models.PositiveBigIntegerField()),
                ('image', models.FileField(upload_to='countries_images/')),
            ],
        ),
    ]
