# Generated by Django 6.0 on 2025-12-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='ticket_price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
