# Generated by Django 6.0 on 2025-12-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_countries_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='territory',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
