# Generated by Django 6.0 on 2025-12-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_countries_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
